### ISSUE TITLE
Not working. Maybe website has been update.

### ISSUE THREAD

**Issue by karanjakhar** [cu-unofficial/uims-api#1]
It's not working and giving an error KeyError: 'd' 
It indicating this line:
attendance = json.loads(response.text)["d"]

**Comment by ritiek** [comment]
You're right. I tried to intercept requests made by my browser and it seems like the website now also expects a session number when a request to fetch attendance information is made, as in https://github.com/cu-unofficial/uims-api/commit/6afa1c383fa531a822f19df4595c60c1c59353db. But I'm still not sure whether this session number of 19201 is hardcoded or depends on something else. 

Let's wait for a few days to see whether this session number changes and ends up breaking the tool yet again, and then we could try to figure out the cause.

Let me know whether the latest commit works for your credentials!

**Comment by karanjakhar** [comment]
It's working now. 
Thanks
