### ISSUE TITLE
Issue with latest PR

### ISSUE THREAD

**Issue by xpt1x** [cu-unofficial/uims-api#10]
I now feel latest addition of PasswordExpired is not right as UIMS after login always do a 302
So status check at that point is not good :confused: 

So, i request kindly rollback for now

**Comment by ritiek** [comment]
I've given you write access so feel free to make a new commit that reverses the changes.

**Comment by xpt1x** [comment]
Ok thanks @ritiek

**Comment by xpt1x** [comment]
I requested a access for Kraken, is it ok ?

**Comment by ritiek** [comment]
Kraken?

**Comment by ritiek** [comment]
Yes, okay. No problem.

**Comment by xpt1x** [comment]
Thanks @ritiek 
Action for now: Reverted to original 
#9 needs fix
