### ISSUE TITLE
How about returning full report of attendance ?

### ISSUE THREAD

**Issue by xpt1x** [cu-unofficial/uims-api#11]
I am about to add this feature to SnapAttendance project
Changed session.py: https://github.com/xpt1x/SnapAttendance/blob/master/uims_api/session.py

Will it be a good idea to add this to this original project as well ?
`Increases fetching time in my testing from 3.5secs -> 5 secs`

**Comment by ritiek** [comment]
How about creating a new method for returning the full attendance? This way we keep the older method for fetching minimal attendance details working too, and the library users would have the freedom to choose whether or not they'd like a trade-off between the full attendance report and additional network request that gets made.

Make a PR and then we could go from there!

**Comment by xpt1x** [comment]
#12 Done 
( Remove vercel please whenever u get time )

**Comment by xpt1x** [comment]
@ritiek please check
