### ISSUE TITLE
Query: Is it an API or web-scrapper ?

### ISSUE THREAD

**Issue by imabp** [cu-unofficial/uims-api#13]
On going throughthis following line [here](https://github.com/cu-unofficial/uims-api/blob/2f569992bf3d8b794b265d3f10f0888d239637dd/uims_api/session.py#L39) 

I feel its web scrapper, then we must be careful for the life cycle of this project.

@ritiek @xpt1x

**Comment by xpt1x** [comment]
Yes its a web scrapper but more of a wrapper, its written in README too
Sorry but I am not able to understand what you are trying to point out here, can u explain @imabp ?

**Comment by imabp** [comment]
If it is a web scraper, if the host change its className of the DOM nodes, the project can get seriously affected.

**Comment by xpt1x** [comment]
Yeah but this is the only way, to do this
And thats why project needs active contributors, to keep it alive
