### ISSUE TITLE
_get_attendance() 

### ISSUE THREAD

**Issue by karanjakhar** [cu-unofficial/uims-api#2]
Could you please explain what this function is doing and how it is working. I am having trouble understanding it. :)

**Comment by ritiek** [comment]
I've pushed a new commit with comments for explanation, in the function:
https://github.com/cu-unofficial/uims-api/blob/34a656227ec733c29c414cb3b0edd9f8ac255262/uims_api/session.py#L72-L107

Let me know if anything isn't clear! Also, there are many tools that you can use for intercepting your browser network-requests, one of which I use is [mitmproxy](https://github.com/mitmproxy/mitmproxy).

**Comment by karanjakhar** [comment]
I tried to use mitmproxy but having trouble working with HTTPS  requests. It works fine with HTTP but I don't know how to get it to work with https. Please help and point me in the right direction. @ritiek

**Comment by ritiek** [comment]
Once you're able to intercept HTTP traffic with mitmproxy, then go to http://mitm.it on the device  making use of the proxy server and install the SSL certificate for your browser. And then you should be able to intercept HTTPS traffic on this device as well. You'll need to repeat this procedure for any device you wish to intercept HTTPS traffic from.

See https://docs.mitmproxy.org/stable/concepts-certificates/ for more info.

**Comment by karanjakhar** [comment]
Thanks buddy
