### ISSUE TITLE
could we use this api to create a crome extension 

### ISSUE THREAD

**Issue by Souvikns** [cu-unofficial/uims-api#4]
I was thinking of building a chrome extension with the help of this API, which will show the attendance of different subjects. 

Tell me your thought on this.

**Comment by Souvikns** [comment]
or a system tray application that does the same thing

**Comment by ritiek** [comment]
Yup, sure! That would be interesting. I'm not sure whether it's a good idea to transpile Python to Javascript for use in Chrome extensions but either way it shouldn't take much work to port this library to Javascript.

**Comment by Souvikns** [comment]
suppose we use this python script and make an API with flask, then we just need to use js to create the front end as a chrome extension

**Comment by ritiek** [comment]
Yup, that would be another way too!

**Comment by Souvikns** [comment]
So like how should we start this project?
